version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:244714571883:task-def/task-def:1"
        LoadBalancerInfo:
          ContainerName: "i-09be886fdf7c4220c"
          ContainerPort: 3000
