version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t docker-repo . 
      - docker tag the-example-app.nodejs:latest 244714571883.dkr.ecr.ap-south-1.amazonaws.com/docker-repo:the-example-app.nodejs
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 244714571883.dkr.ecr.ap-south-1.amazonaws.com/docker-repo:the-example-app.nodejs
